#!/usr/bin/env python3
"""Generate SKILLS_INDEX.md — a browsable index of all skills in the repository."""

import sys
from pathlib import Path
from collections import defaultdict

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml")
    sys.exit(1)

REPO_ROOT = Path(__file__).parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
OUTPUT = REPO_ROOT / "SKILLS_INDEX.md"

DOMAIN_EMOJI = {
    "physics": "⚛️",
    "biology": "🧬",
    "chemistry": "⚗️",
    "mathematics": "➗",
    "neuroscience": "🧠",
    "computer-science": "💻",
    "cross-domain": "🔀",
}

STATUS_BADGE = {
    "draft": "![draft](https://img.shields.io/badge/status-draft-yellow)",
    "reviewed": "![reviewed](https://img.shields.io/badge/status-reviewed-blue)",
    "verified": "![verified](https://img.shields.io/badge/status-verified-green)",
}


def load_skill(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        front = yaml.safe_load(parts[1])
        if isinstance(front, dict):
            front["_path"] = str(path.relative_to(REPO_ROOT))
            return front
    except yaml.YAMLError:
        pass
    return None


def main():
    by_domain: dict[str, list[dict]] = defaultdict(list)

    for skill_file in sorted(SKILLS_DIR.rglob("*.md")):
        if skill_file.name.startswith("_") or skill_file.name == "README.md":
            continue
        skill = load_skill(skill_file)
        if skill:
            domain = skill.get("domain", "cross-domain")
            by_domain[domain].append(skill)

    lines = [
        "# Skills Index",
        "",
        "> Auto-generated by `tools/build_index.py`. Do not edit manually.",
        "",
        f"**Total skills:** {sum(len(v) for v in by_domain.values())}",
        "",
    ]

    for domain in sorted(by_domain.keys()):
        emoji = DOMAIN_EMOJI.get(domain, "🔬")
        skills = sorted(by_domain[domain], key=lambda s: s.get("name", ""))
        lines.append(f"## {emoji} {domain.replace('-', ' ').title()}")
        lines.append("")
        lines.append("| Skill | Description | Level | Status | Author |")
        lines.append("|---|---|---|---|---|")
        for s in skills:
            name = s.get("name", "—")
            desc = s.get("description", "—").replace("\n", " ").strip()[:80]
            level = s.get("expertise_level", "—")
            status = s.get("status", "draft")
            badge = STATUS_BADGE.get(status, status)
            author = s.get("author", "—")
            path = s.get("_path", "")
            lines.append(f"| [{name}]({path}) | {desc} | {level} | {badge} | {author} |")
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {OUTPUT}")


if __name__ == "__main__":
    main()
